
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'IDENTIFIER INT LBRACE LPAREN MAIN RBRACE RPAREN SEMICOLONprogram : statementstatement : INT IDENTIFIER SEMICOLON\n                 | MAIN LPAREN RPAREN LBRACE statement RBRACE'
    
_lr_action_items = {'INT':([0,9,],[3,3,]),'MAIN':([0,9,],[4,4,]),'$end':([1,2,7,11,],[0,-1,-2,-3,]),'IDENTIFIER':([3,],[5,]),'LPAREN':([4,],[6,]),'SEMICOLON':([5,],[7,]),'RPAREN':([6,],[8,]),'RBRACE':([7,10,11,],[-2,11,-3,]),'LBRACE':([8,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,9,],[2,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program','app.py',37),
  ('statement -> INT IDENTIFIER SEMICOLON','statement',3,'p_statement','app.py',41),
  ('statement -> MAIN LPAREN RPAREN LBRACE statement RBRACE','statement',6,'p_statement','app.py',42),
]
